//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliCountry.Facturacion.Negocio.Comun.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReglasNegocio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReglasNegocio() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CliCountry.Facturacion.Negocio.Comun.Recursos.ReglasNegocio", typeof(ReglasNegocio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al almacenar el criterio de aproximación..
        /// </summary>
        internal static string Aproximacion_ErrorGuardarCriterio {
            get {
                return ResourceManager.GetString("Aproximacion_ErrorGuardarCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al almacenar los límites de intervalos..
        /// </summary>
        internal static string Aproximacion_ErrorGuardarIntervalo {
            get {
                return ResourceManager.GetString("Aproximacion_ErrorGuardarIntervalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un error al actualizar el criterio de aproximación.
        /// </summary>
        internal static string Aproximaciones_MsjErrActualizar {
            get {
                return ResourceManager.GetString("Aproximaciones_MsjErrActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un error al crear el criterio de aproximación.
        /// </summary>
        internal static string Aproximaciones_MsjErrCrear {
            get {
                return ResourceManager.GetString("Aproximaciones_MsjErrCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un error al eliminar los límites..
        /// </summary>
        internal static string Aproximaciones_MsjErrEliminarInt {
            get {
                return ResourceManager.GetString("Aproximaciones_MsjErrEliminarInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un error al guardar los límites..
        /// </summary>
        internal static string Aproximaciones_MsjErrGuardarInt {
            get {
                return ResourceManager.GetString("Aproximaciones_MsjErrGuardarInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo de convenio no clínico debe ser instanciado con el IdManual.
        /// </summary>
        internal static string ConvenioNoClinico_NoInstanciado {
            get {
                return ResourceManager.GetString("ConvenioNoClinico_NoInstanciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El producto no tiene una tarifa definida IdProducto:{0} Nombre:{1} Atención:{2}.
        /// </summary>
        internal static string DetalleTarifa_AjusteTarifa {
            get {
                return ResourceManager.GetString("DetalleTarifa_AjusteTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra configurado el valor para el  IdProducto:{0} Nombre:{1} Atención:{2}, relacionado al ajuste de tarifa.
        /// </summary>
        internal static string DetalleTarifa_Porcentaje {
            get {
                return ResourceManager.GetString("DetalleTarifa_Porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregado.
        /// </summary>
        internal static string EstadoAgregado {
            get {
                return ResourceManager.GetString("EstadoAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrado.
        /// </summary>
        internal static string EstadoBorrado {
            get {
                return ResourceManager.GetString("EstadoBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo de grupo de producto debe tener un valor o ser instanciado con el constructor por defecto.
        /// </summary>
        internal static string GrupoProducto_NoInstanciado {
            get {
                return ResourceManager.GetString("GrupoProducto_NoInstanciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra configurado la homologación para el producto {0} Atención:{1}.
        /// </summary>
        internal static string HomologacionProducto_SinDato {
            get {
                return ResourceManager.GetString("HomologacionProducto_SinDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un error al crear el detalle del nivel de complejidad..
        /// </summary>
        internal static string NivelComplejidad_ErrorCrearDetalle {
            get {
                return ResourceManager.GetString("NivelComplejidad_ErrorCrearDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un error al crear el nivel de complejidad.
        /// </summary>
        internal static string NivelComplejidad_ErrorCrearNivel {
            get {
                return ResourceManager.GetString("NivelComplejidad_ErrorCrearNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El producto {0} - {1} No tiene nivel de complejidad configurado.
        /// </summary>
        internal static string NivelComplejidad_Nivel {
            get {
                return ResourceManager.GetString("NivelComplejidad_Nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar.
        /// </summary>
        internal static string OperacionInsertar {
            get {
                return ResourceManager.GetString("OperacionInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string OperacionModificar {
            get {
                return ResourceManager.GetString("OperacionModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo de producto debe tener un valor o ser instanciado con el constructor por defecto.
        /// </summary>
        internal static string Producto_NoInstanciado {
            get {
                return ResourceManager.GetString("Producto_NoInstanciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F.
        /// </summary>
        internal static string Tarifas_TipoFacturacion {
            get {
                return ResourceManager.GetString("Tarifas_TipoFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T.
        /// </summary>
        internal static string Tarifas_TipoTarifas {
            get {
                return ResourceManager.GetString("Tarifas_TipoTarifas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NA.
        /// </summary>
        internal static string TipoComponente_NA {
            get {
                return ResourceManager.GetString("TipoComponente_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra configurada la unidad para la fecha de vigencia {0} del manual {1}.
        /// </summary>
        internal static string UnidadVenta {
            get {
                return ResourceManager.GetString("UnidadVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible realizar la asociación de ventas, vuelva  a intentarlo nuevamente.
        /// </summary>
        internal static string VentasProductoRelacion {
            get {
                return ResourceManager.GetString("VentasProductoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un error al insertar las vigencias de tarifa..
        /// </summary>
        internal static string VigenciaTarifa_MsjErrCrearVigencias {
            get {
                return ResourceManager.GetString("VigenciaTarifa_MsjErrCrearVigencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible realizar la vinculación del Venta {0} Atención Padre {1} Atención Hija {2}.
        /// </summary>
        internal static string VinculacionVentas {
            get {
                return ResourceManager.GetString("VinculacionVentas", resourceCulture);
            }
        }
    }
}
