//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliCountry.Facturacion.Web.WebExterno.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01")]
        public string General_CodigoEntidad {
            get {
                return ((string)(this["General_CodigoEntidad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int TipoMovimiento_IdentificadorMovimientoNumerado {
            get {
                return ((int)(this["TipoMovimiento_IdentificadorMovimientoNumerado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FacturasRelacionActi")]
        public string TipoMovimiento_CodigoPantalla {
            get {
                return ((string)(this["TipoMovimiento_CodigoPantalla"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FacturasRelacionActi")]
        public string TipoMovimiento_CodigoPantallaDetalle {
            get {
                return ((string)(this["TipoMovimiento_CodigoPantallaDetalle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short TipoMovimiento_IndicadorPantallaActivo {
            get {
                return ((short)(this["TipoMovimiento_IndicadorPantallaActivo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TipoAtencion_IndicadorEstadoHabilitado {
            get {
                return ((bool)(this["TipoAtencion_IndicadorEstadoHabilitado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Formato_IdentificadorEstadoFormato {
            get {
                return ((bool)(this["Formato_IdentificadorEstadoFormato"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Entidad_IndicadorHabilitadoContrato {
            get {
                return ((bool)(this["Entidad_IndicadorHabilitadoContrato"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Entidad_IndicadorFacturaRelacion {
            get {
                return ((bool)(this["Entidad_IndicadorFacturaRelacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Entidad_IndicadorHabilitadoTercero {
            get {
                return ((bool)(this["Entidad_IndicadorHabilitadoTercero"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Seccion_CodigoSede {
            get {
                return ((int)(this["Seccion_CodigoSede"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Seccion_IdEstadoOrgan {
            get {
                return ((int)(this["Seccion_IdEstadoOrgan"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01")]
        public string Seccion_CodigoEstadoOrgan {
            get {
                return ((string)(this["Seccion_CodigoEstadoOrgan"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public short TipoAtencion_IdentificadorAtencionTipoBase {
            get {
                return ((short)(this["TipoAtencion_IdentificadorAtencionTipoBase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short FacturacionRelacion_AtencionOrdenPrioridad {
            get {
                return ((short)(this["FacturacionRelacion_AtencionOrdenPrioridad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte ProcesoFactura_EstadoPendiente {
            get {
                return ((byte)(this["ProcesoFactura_EstadoPendiente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,3")]
        public string FacturaRelacion_TipoRelacion {
            get {
                return ((string)(this["FacturaRelacion_TipoRelacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3887")]
        public short UsuarioFirma_Facturacion {
            get {
                return ((short)(this["UsuarioFirma_Facturacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SISADM,BILFA1,BILFA2")]
        public string UsuarioRoles_DesbloquearAtencion {
            get {
                return ((string)(this["UsuarioRoles_DesbloquearAtencion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public short Paginacion_CantidadBotones {
            get {
                return ((short)(this["Paginacion_CantidadBotones"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public short Paginacion_CantidadRegistrosPagina {
            get {
                return ((short)(this["Paginacion_CantidadRegistrosPagina"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("057011001")]
        public string CodigoCiudadCliente {
            get {
                return ((string)(this["CodigoCiudadCliente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Uno")]
        public string Nivel_Cliente {
            get {
                return ((string)(this["Nivel_Cliente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public string TransaccionVentasQuirurgicas {
            get {
                return ((string)(this["TransaccionVentasQuirurgicas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75,146")]
        public string TransaccionVentasMedicamentosInsumos {
            get {
                return ((string)(this["TransaccionVentasMedicamentosInsumos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int CondicionCubrimiento_IdPagina {
            get {
                return ((int)(this["CondicionCubrimiento_IdPagina"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CondicionCubrimiento_IdMaestra {
            get {
                return ((int)(this["CondicionCubrimiento_IdMaestra"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,2,3,4,5,6")]
        public string FacturaActividades_TipoRelacion {
            get {
                return ((string)(this["FacturaActividades_TipoRelacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public string CondicionesFacturacion_Tipo {
            get {
                return ((string)(this["CondicionesFacturacion_Tipo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string CondicionesTarifa_Tipo {
            get {
                return ((string)(this["CondicionesTarifa_Tipo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CondicionesTarifa_AjusteTarifa {
            get {
                return ((int)(this["CondicionesTarifa_AjusteTarifa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J")]
        public string TipoPersona_Juridica {
            get {
                return ((string)(this["TipoPersona_Juridica"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string TipoPersona_Natural {
            get {
                return ((string)(this["TipoPersona_Natural"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ventas No Clinica")]
        public string FacturacionNoClinica_Transaccion {
            get {
                return ((string)(this["FacturacionNoClinica_Transaccion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ventas No QX")]
        public string FacturacionNoQX_Transaccion {
            get {
                return ((string)(this["FacturacionNoQX_Transaccion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ventas QX")]
        public string FacturacionQX_Transaccion {
            get {
                return ((string)(this["FacturacionQX_Transaccion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short ModuloWeb_IdModulo {
            get {
                return ((short)(this["ModuloWeb_IdModulo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string AnchoCodigoBarras {
            get {
                return ((string)(this["AnchoCodigoBarras"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public string LargoCodigoBarras {
            get {
                return ((string)(this["LargoCodigoBarras"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("830005028")]
        public string NitCountryParticular {
            get {
                return ((string)(this["NitCountryParticular"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/default.aspx,/Facturacion/ReporteEstadoCuenta.aspx,/Facturacion/ReporteEstadoCue" +
            "ntaMultiple.aspx,/Facturacion/ReporteEstadoCuentaPaquetes.aspx,/Facturacion/Repo" +
            "rteRelacionPaquetes.aspx,/Facturacion/ReporteVenta.aspx")]
        public string PermisosEspeciales {
            get {
                return ((string)(this["PermisosEspeciales"]));
            }
        }
    }
}
