//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdministradorFacActividades {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministradorFacActividades() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdministradorFacActividades", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención:.
        /// </summary>
        internal static string FacActividad_Atencion {
            get {
                return ResourceManager.GetString("FacActividad_Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturar.
        /// </summary>
        internal static string FacActividad_ChkFacturar {
            get {
                return ResourceManager.GetString("FacActividad_ChkFacturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar.
        /// </summary>
        internal static string FacActividad_ChkGenerar {
            get {
                return ResourceManager.GetString("FacActividad_ChkGenerar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        internal static string FacActividad_ChkSeleccionar {
            get {
                return ResourceManager.GetString("FacActividad_ChkSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CortesFacturacion.aspx.
        /// </summary>
        internal static string FacActividad_CortesFacturacion {
            get {
                return ResourceManager.GetString("FacActividad_CortesFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        internal static string FacActividad_GrvChkActivo {
            get {
                return ResourceManager.GetString("FacActividad_GrvChkActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturar.
        /// </summary>
        internal static string FacActividad_GrvChkFacturar {
            get {
                return ResourceManager.GetString("FacActividad_GrvChkFacturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar.
        /// </summary>
        internal static string FacActividad_GrvChkGenerar {
            get {
                return ResourceManager.GetString("FacActividad_GrvChkGenerar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        internal static string FacActividad_GrvChkSeleccionar {
            get {
                return ResourceManager.GetString("FacActividad_GrvChkSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato.
        /// </summary>
        internal static string FacActividad_GrvEntidad_Contrato {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad.
        /// </summary>
        internal static string FacActividad_GrvEntidad_Entidad {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string FacActividad_GrvEntidad_ID {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Atención.
        /// </summary>
        internal static string FacActividad_GrvEntidad_IdAtencion {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_IdAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Plan.
        /// </summary>
        internal static string FacActividad_GrvEntidad_IdPlan {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_IdPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación.
        /// </summary>
        internal static string FacActividad_GrvEntidad_Observacion {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden.
        /// </summary>
        internal static string FacActividad_GrvEntidad_Orden {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan.
        /// </summary>
        internal static string FacActividad_GrvEntidad_Plan {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención Enlazada.
        /// </summary>
        internal static string FacActividad_GrvVentas_AtencionEnlazada {
            get {
                return ResourceManager.GetString("FacActividad_GrvVentas_AtencionEnlazada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Venta.
        /// </summary>
        internal static string FacActividad_GrvVentas_FechaVenta {
            get {
                return ResourceManager.GetString("FacActividad_GrvVentas_FechaVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de Venta.
        /// </summary>
        internal static string FacActividad_GrvVentas_NumeroVenta {
            get {
                return ResourceManager.GetString("FacActividad_GrvVentas_NumeroVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción.
        /// </summary>
        internal static string FacActividad_GrvVentas_Transaccion {
            get {
                return ResourceManager.GetString("FacActividad_GrvVentas_Transaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación de Consumo.
        /// </summary>
        internal static string FacActividad_GrvVentas_UbicacionConsumo {
            get {
                return ResourceManager.GetString("FacActividad_GrvVentas_UbicacionConsumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación de Entrega.
        /// </summary>
        internal static string FacActividad_GrvVentas_UbicacionEntrega {
            get {
                return ResourceManager.GetString("FacActividad_GrvVentas_UbicacionEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Movimientos Activos.
        /// </summary>
        internal static string FacActividad_GuardarMovimientos {
            get {
                return ResourceManager.GetString("FacActividad_GuardarMovimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movimientos Activos.
        /// </summary>
        internal static string FacActividad_MovimientosActivos {
            get {
                return ResourceManager.GetString("FacActividad_MovimientosActivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha realizado la actualización de los movimientos.
        /// </summary>
        internal static string FacActividad_MsjActualizoMovimiento {
            get {
                return ResourceManager.GetString("FacActividad_MsjActualizoMovimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha realizado la actualización de los movimientos.
        /// </summary>
        internal static string FacActividad_MsjNoActualizoMovimiento {
            get {
                return ResourceManager.GetString("FacActividad_MsjNoActualizoMovimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Documento:.
        /// </summary>
        internal static string FacActividad_NoDocumento {
            get {
                return ResourceManager.GetString("FacActividad_NoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paciente:.
        /// </summary>
        internal static string FacActividad_Paciente {
            get {
                return ResourceManager.GetString("FacActividad_Paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pestaña - Entidades.
        /// </summary>
        internal static string FacActividad_PestanaEntidades {
            get {
                return ResourceManager.GetString("FacActividad_PestanaEntidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pestaña - Ventas.
        /// </summary>
        internal static string FacActividad_PestanaVentas {
            get {
                return ResourceManager.GetString("FacActividad_PestanaVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ReporteEstadoCuentaMultiple.aspx.
        /// </summary>
        internal static string FacActividad_ReporteEstadoCuenta {
            get {
                return ResourceManager.GetString("FacActividad_ReporteEstadoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~\ReportesFacturacion\FacturacionAgrupadaActividades.rdlc.
        /// </summary>
        internal static string FacActividad_RptEstadoCuentaAgrupado {
            get {
                return ResourceManager.GetString("FacActividad_RptEstadoCuentaAgrupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~\ReportesFacturacion\FacturacionDetalladaActividades.rdlc.
        /// </summary>
        internal static string FacActividad_RptEstadoCuentaDetallado {
            get {
                return ResourceManager.GetString("FacActividad_RptEstadoCuentaDetallado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~\ReportesFacturacion\FacturacionAgrupadaPaquetes.rdlc.
        /// </summary>
        internal static string FacActividad_RptEstadoCuentaPaquetesAgrupado {
            get {
                return ResourceManager.GetString("FacActividad_RptEstadoCuentaPaquetesAgrupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~\ReportesFacturacion\ReimpresionAgrupadaActividades.rdlc.
        /// </summary>
        internal static string FacActividad_RptEstadoReimpresionCuentaAgrup {
            get {
                return ResourceManager.GetString("FacActividad_RptEstadoReimpresionCuentaAgrup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~\ReportesFacturacion\ReimpresionDetalladaActividades.rdlc.
        /// </summary>
        internal static string FacActividad_RptEstadoReimpresionCuentaDetallado {
            get {
                return ResourceManager.GetString("FacActividad_RptEstadoReimpresionCuentaDetallado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sección:.
        /// </summary>
        internal static string FacActividad_Seccion {
            get {
                return ResourceManager.GetString("FacActividad_Seccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidades.
        /// </summary>
        internal static string FacActividad_TabEntidades {
            get {
                return ResourceManager.GetString("FacActividad_TabEntidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tercero / Cliente.
        /// </summary>
        internal static string FacActividad_TabResponsable {
            get {
                return ResourceManager.GetString("FacActividad_TabResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        internal static string FacActividad_TabVentas {
            get {
                return ResourceManager.GetString("FacActividad_TabVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de atención.
        /// </summary>
        internal static string FacActividad_TipoAtencion {
            get {
                return ResourceManager.GetString("FacActividad_TipoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo movimiento factura:.
        /// </summary>
        internal static string FacActividad_TipoMovimientoFactura {
            get {
                return ResourceManager.GetString("FacActividad_TipoMovimientoFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturación por Actividades.
        /// </summary>
        internal static string FacActividad_Titulo {
            get {
                return ResourceManager.GetString("FacActividad_Titulo", resourceCulture);
            }
        }
    }
}
