//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CondicionesFacturacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CondicionesFacturacion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CondicionesFacturacion", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CodIndAct.
        /// </summary>
        internal static string CondicionesFacturacion_Activo {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id. Atencion.
        /// </summary>
        internal static string CondicionesFacturacion_Atencion {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        internal static string CondicionesFacturacion_CActivo {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_CActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activa o desactiva la condición de facturación.
        /// </summary>
        internal static string CondicionesFacturacion_ChkActivo {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_ChkActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible ejecutar esta accion , existe Una Condición de Facturación Activa para esta atención!.
        /// </summary>
        internal static string CondicionesFacturacion_conficuracionExistente {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_conficuracionExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato.
        /// </summary>
        internal static string CondicionesFacturacion_Contrato {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad.
        /// </summary>
        internal static string CondicionesFacturacion_Entidad {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan.
        /// </summary>
        internal static string CondicionesFacturacion_Plan {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Relación.
        /// </summary>
        internal static string CondicionesFacturacion_TipoRelacion {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_TipoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condiciones de Facturación.
        /// </summary>
        internal static string CondicionesFacturacion_Titulo {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Condición de Facturación.
        /// </summary>
        internal static string CondicionesFacturacion_TituloActualizar {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_TituloActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta Condición de Facturación.
        /// </summary>
        internal static string CondicionesFacturacion_TituloConsulta {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_TituloConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Condición de Facturación.
        /// </summary>
        internal static string CondicionesFacturacion_TituloCrear {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_TituloCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Condición de Facturación.
        /// </summary>
        internal static string CondicionesFacturacion_TituloModificar {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_TituloModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string FacActividad_GrvCondicionesFacturacion_Descripcion {
            get {
                return ResourceManager.GetString("FacActividad_GrvCondicionesFacturacion_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación Atención.
        /// </summary>
        internal static string FacActividad_GrvCondicionesFacturacion_IdAtencion {
            get {
                return ResourceManager.GetString("FacActividad_GrvCondicionesFacturacion_IdAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F.
        /// </summary>
        internal static string FacActividad_GrvCondicionesFacturacion_Tipo {
            get {
                return ResourceManager.GetString("FacActividad_GrvCondicionesFacturacion_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Relación.
        /// </summary>
        internal static string FacActividad_GrvCondicionesFacturacion_TipoRelacion {
            get {
                return ResourceManager.GetString("FacActividad_GrvCondicionesFacturacion_TipoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        internal static string FacActividad_GrvCondicionesFacturacion_Valor {
            get {
                return ResourceManager.GetString("FacActividad_GrvCondicionesFacturacion_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigencia.
        /// </summary>
        internal static string FacActividad_GrvCondicionesFacturacion_Vigencia {
            get {
                return ResourceManager.GetString("FacActividad_GrvCondicionesFacturacion_Vigencia", resourceCulture);
            }
        }
    }
}
