//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefinirExclusiones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefinirExclusiones() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DefinirExclusiones", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        internal static string DefinirExclusiones_Activo {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Exclusión.
        /// </summary>
        internal static string DefinirExclusiones_Actualizar {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alterno.
        /// </summary>
        internal static string DefinirExclusiones_Alterno {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Alterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención No..
        /// </summary>
        internal static string DefinirExclusiones_AtencionNo {
            get {
                return ResourceManager.GetString("DefinirExclusiones_AtencionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adicionar.
        /// </summary>
        internal static string DefinirExclusiones_BtnAdicionar {
            get {
                return ResourceManager.GetString("DefinirExclusiones_BtnAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Exclusión.
        /// </summary>
        internal static string DefinirExclusiones_BtnAdicionarToolTip {
            get {
                return ResourceManager.GetString("DefinirExclusiones_BtnAdicionarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar.
        /// </summary>
        internal static string DefinirExclusiones_BtnConsultar {
            get {
                return ResourceManager.GetString("DefinirExclusiones_BtnConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar.
        /// </summary>
        internal static string DefinirExclusiones_BtnConsultarToolTip {
            get {
                return ResourceManager.GetString("DefinirExclusiones_BtnConsultarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Componente.
        /// </summary>
        internal static string DefinirExclusiones_Componente {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Componente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Exclusion.
        /// </summary>
        internal static string DefinirExclusiones_Consultar {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato.
        /// </summary>
        internal static string DefinirExclusiones_Contrato {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Exclusión.
        /// </summary>
        internal static string DefinirExclusiones_Crear {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad.
        /// </summary>
        internal static string DefinirExclusiones_Entidad {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de Producto.
        /// </summary>
        internal static string DefinirExclusiones_GrupoProducto {
            get {
                return ResourceManager.GetString("DefinirExclusiones_GrupoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id. Atención.
        /// </summary>
        internal static string DefinirExclusiones_IdAtencion {
            get {
                return ResourceManager.GetString("DefinirExclusiones_IdAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador Producto Alterno.
        /// </summary>
        internal static string DefinirExclusiones_IdProductoAlterno {
            get {
                return ResourceManager.GetString("DefinirExclusiones_IdProductoAlterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual.
        /// </summary>
        internal static string DefinirExclusiones_Manual {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Niveles.
        /// </summary>
        internal static string DefinirExclusiones_Niveles {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Niveles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel final.
        /// </summary>
        internal static string DefinirExclusiones_NivelFinal {
            get {
                return ResourceManager.GetString("DefinirExclusiones_NivelFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel incial.
        /// </summary>
        internal static string DefinirExclusiones_NivelInicial {
            get {
                return ResourceManager.GetString("DefinirExclusiones_NivelInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Tarifa.
        /// </summary>
        internal static string DefinirExclusiones_NombreTarifa {
            get {
                return ResourceManager.GetString("DefinirExclusiones_NombreTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan.
        /// </summary>
        internal static string DefinirExclusiones_Plan {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        internal static string DefinirExclusiones_Producto {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango final orden de Nivel.
        /// </summary>
        internal static string DefinirExclusiones_RangoFinalOrdenNivel {
            get {
                return ResourceManager.GetString("DefinirExclusiones_RangoFinalOrdenNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango max. nivel.
        /// </summary>
        internal static string DefinirExclusiones_RangoMaximo {
            get {
                return ResourceManager.GetString("DefinirExclusiones_RangoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango min. nivel.
        /// </summary>
        internal static string DefinirExclusiones_RangoMinimo {
            get {
                return ResourceManager.GetString("DefinirExclusiones_RangoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango de orden de nivel.
        /// </summary>
        internal static string DefinirExclusiones_RangoOrdenNivel {
            get {
                return ResourceManager.GetString("DefinirExclusiones_RangoOrdenNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio.
        /// </summary>
        internal static string DefinirExclusiones_Servicio {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarifa.
        /// </summary>
        internal static string DefinirExclusiones_Tarifa {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Tarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de atención.
        /// </summary>
        internal static string DefinirExclusiones_TipoAtencion {
            get {
                return ResourceManager.GetString("DefinirExclusiones_TipoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Producto.
        /// </summary>
        internal static string DefinirExclusiones_TipoProducto {
            get {
                return ResourceManager.GetString("DefinirExclusiones_TipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Relación.
        /// </summary>
        internal static string DefinirExclusiones_TipoRelacion {
            get {
                return ResourceManager.GetString("DefinirExclusiones_TipoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir Exclusiones.
        /// </summary>
        internal static string DefinirExclusiones_Titulo {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad.
        /// </summary>
        internal static string DefinirExclusiones_Unidad {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Unidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Venta.
        /// </summary>
        internal static string DefinirExclusiones_Venta {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigencia.
        /// </summary>
        internal static string DefinirExclusiones_Vigencia {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Vigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigencia Tarifa.
        /// </summary>
        internal static string DefinirExclusiones_VigenciaTarifa {
            get {
                return ResourceManager.GetString("DefinirExclusiones_VigenciaTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de Producto.
        /// </summary>
        internal static string Definir_Eclusiones_Grupo_Producto {
            get {
                return ResourceManager.GetString("Definir_Eclusiones_Grupo_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase de Servicio.
        /// </summary>
        internal static string Definir_Exclusiones_Clase_Servicio {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Clase_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador.
        /// </summary>
        internal static string Definir_Exclusiones_Identificador {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual.
        /// </summary>
        internal static string Definir_Exclusiones_Manual {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máximo.
        /// </summary>
        internal static string Definir_Exclusiones_Maximo {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Maximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo.
        /// </summary>
        internal static string Definir_Exclusiones_Minimo {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Minimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel 2.
        /// </summary>
        internal static string Definir_Exclusiones_NivelDos {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_NivelDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel 1.
        /// </summary>
        internal static string Definir_Exclusiones_NivelUno {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_NivelUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto Alterno.
        /// </summary>
        internal static string Definir_Exclusiones_Producto_Alterno {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Producto_Alterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades.
        /// </summary>
        internal static string Definir_Exclusiones_Unidades {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Unidades", resourceCulture);
            }
        }
    }
}
