//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descuentos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descuentos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Descuentos", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string CondicionesCubrimientos_Descripcion {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        internal static string CondicionesCubrimientos_Valor {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigencia.
        /// </summary>
        internal static string CondicionesCubrimientos_Vigencia {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Vigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Tarifa.
        /// </summary>
        internal static string DefinirCondicionesTarifa_NombreTarifa {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_NombreTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir Condiciones Tarifa.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Titulo {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigencia Condición.
        /// </summary>
        internal static string DefinirCondicionesTarifa_VigenciaCondicion {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_VigenciaCondicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VigenciaTarifa.
        /// </summary>
        internal static string DefinirCondicionesTarifa_VigenciaTarifa {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_VigenciaTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        internal static string Descuentos_Activo {
            get {
                return ResourceManager.GetString("Descuentos_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención.
        /// </summary>
        internal static string Descuentos_Atencion {
            get {
                return ResourceManager.GetString("Descuentos_Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Componente.
        /// </summary>
        internal static string Descuentos_Componente {
            get {
                return ResourceManager.GetString("Descuentos_Componente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible ejecutar esta accion , existe un Descuento con esas mismas caracteristicas!.
        /// </summary>
        internal static string Descuentos_ConfiguracionExiste {
            get {
                return ResourceManager.GetString("Descuentos_ConfiguracionExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Descuento.
        /// </summary>
        internal static string Descuentos_Consultar {
            get {
                return ResourceManager.GetString("Descuentos_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato .
        /// </summary>
        internal static string Descuentos_Contrato {
            get {
                return ResourceManager.GetString("Descuentos_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Descuento.
        /// </summary>
        internal static string Descuentos_CrearDescuento {
            get {
                return ResourceManager.GetString("Descuentos_CrearDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cubrimiento.
        /// </summary>
        internal static string Descuentos_Cubrimiento {
            get {
                return ResourceManager.GetString("Descuentos_Cubrimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad.
        /// </summary>
        internal static string Descuentos_Entidad {
            get {
                return ResourceManager.GetString("Descuentos_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al cargar la información..
        /// </summary>
        internal static string Descuentos_ErrorCargueInformacion {
            get {
                return ResourceManager.GetString("Descuentos_ErrorCargueInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final.
        /// </summary>
        internal static string Descuentos_FechaFinal {
            get {
                return ResourceManager.GetString("Descuentos_FechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicial.
        /// </summary>
        internal static string Descuentos_FechaInicial {
            get {
                return ResourceManager.GetString("Descuentos_FechaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de Producto.
        /// </summary>
        internal static string Descuentos_GrupoProducto {
            get {
                return ResourceManager.GetString("Descuentos_GrupoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID  Atencion.
        /// </summary>
        internal static string Descuentos_IAtencion {
            get {
                return ResourceManager.GetString("Descuentos_IAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Condiciones Cubrimientos.
        /// </summary>
        internal static string Descuentos_IdCondicionesCubrimientos {
            get {
                return ResourceManager.GetString("Descuentos_IdCondicionesCubrimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Descuentos.
        /// </summary>
        internal static string Descuentos_IdDescuento {
            get {
                return ResourceManager.GetString("Descuentos_IdDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador.
        /// </summary>
        internal static string Descuentos_Identificador {
            get {
                return ResourceManager.GetString("Descuentos_Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Descuento.
        /// </summary>
        internal static string Descuentos_ModificarDescuento {
            get {
                return ResourceManager.GetString("Descuentos_ModificarDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha realizado la actualización del descuento.
        /// </summary>
        internal static string Descuentos_MsjActualizacion {
            get {
                return ResourceManager.GetString("Descuentos_MsjActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible realizar la actualización del descuento.
        /// </summary>
        internal static string Descuentos_MsjActualizacionError {
            get {
                return ResourceManager.GetString("Descuentos_MsjActualizacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha realizado la creación del descuento {0} .
        /// </summary>
        internal static string Descuentos_MsjInsercion {
            get {
                return ResourceManager.GetString("Descuentos_MsjInsercion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan.
        /// </summary>
        internal static string Descuentos_Plan {
            get {
                return ResourceManager.GetString("Descuentos_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        internal static string Descuentos_Producto {
            get {
                return ResourceManager.GetString("Descuentos_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Producto.
        /// </summary>
        internal static string Descuentos_TipoProducto {
            get {
                return ResourceManager.GetString("Descuentos_TipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Relación.
        /// </summary>
        internal static string Descuentos_TipoRelacion {
            get {
                return ResourceManager.GetString("Descuentos_TipoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descuentos de contratos.
        /// </summary>
        internal static string Descuentos_Titulo {
            get {
                return ResourceManager.GetString("Descuentos_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condiciones Cubrimientos.
        /// </summary>
        internal static string Descuentos_TituloCondicionesCubrimientos {
            get {
                return ResourceManager.GetString("Descuentos_TituloCondicionesCubrimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar descuento.
        /// </summary>
        internal static string Descuentos_TituloConsultar {
            get {
                return ResourceManager.GetString("Descuentos_TituloConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear descuento.
        /// </summary>
        internal static string Descuentos_TituloCrear {
            get {
                return ResourceManager.GetString("Descuentos_TituloCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar descuento.
        /// </summary>
        internal static string Descuentos_TituloModificar {
            get {
                return ResourceManager.GetString("Descuentos_TituloModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        internal static string Descuentos_Valor {
            get {
                return ResourceManager.GetString("Descuentos_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Descuentos.
        /// </summary>
        internal static string Descuentos_ValorDescuentos {
            get {
                return ResourceManager.GetString("Descuentos_ValorDescuentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualización.
        /// </summary>
        internal static string Descuentos_Visualizacion {
            get {
                return ResourceManager.GetString("Descuentos_Visualizacion", resourceCulture);
            }
        }
    }
}
