//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exclusiones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exclusiones() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Exclusiones", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exclusión Activa.
        /// </summary>
        internal static string Exclusiones_Activa {
            get {
                return ResourceManager.GetString("Exclusiones_Activa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Exclusiones_BtnSalir {
            get {
                return ResourceManager.GetString("Exclusiones_BtnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Exclusiones_BtnSalirToolTip {
            get {
                return ResourceManager.GetString("Exclusiones_BtnSalirToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de Producto.
        /// </summary>
        internal static string Exclusiones_GrupoProducto {
            get {
                return ResourceManager.GetString("Exclusiones_GrupoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar.
        /// </summary>
        internal static string Exclusiones_GrvChkAplicar {
            get {
                return ResourceManager.GetString("Exclusiones_GrvChkAplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar Exclusión.
        /// </summary>
        internal static string Exclusiones_GrvChkAplicarToolTip {
            get {
                return ResourceManager.GetString("Exclusiones_GrvChkAplicarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Exclusión.
        /// </summary>
        internal static string Exclusiones_IdExclusion {
            get {
                return ResourceManager.GetString("Exclusiones_IdExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual ó Contrato.
        /// </summary>
        internal static string Exclusiones_ManualOContrato {
            get {
                return ResourceManager.GetString("Exclusiones_ManualOContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        internal static string Exclusiones_Producto {
            get {
                return ResourceManager.GetString("Exclusiones_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto Alterno.
        /// </summary>
        internal static string Exclusiones_ProductoAlterno {
            get {
                return ResourceManager.GetString("Exclusiones_ProductoAlterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio.
        /// </summary>
        internal static string Exclusiones_Servicio {
            get {
                return ResourceManager.GetString("Exclusiones_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Atención.
        /// </summary>
        internal static string Exclusiones_TipoAtencion {
            get {
                return ResourceManager.GetString("Exclusiones_TipoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Producto.
        /// </summary>
        internal static string Exclusiones_TipoProducto {
            get {
                return ResourceManager.GetString("Exclusiones_TipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Exclusión.
        /// </summary>
        internal static string Exclusiones_TitConsultar {
            get {
                return ResourceManager.GetString("Exclusiones_TitConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Exclusión.
        /// </summary>
        internal static string Exclusiones_TitCrear {
            get {
                return ResourceManager.GetString("Exclusiones_TitCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Exclusión.
        /// </summary>
        internal static string Exclusiones_TitModificar {
            get {
                return ResourceManager.GetString("Exclusiones_TitModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir Exclusiones por Contrato y Manual.
        /// </summary>
        internal static string Exclusiones_Titulo {
            get {
                return ResourceManager.GetString("Exclusiones_Titulo", resourceCulture);
            }
        }
    }
}
