//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reportes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reportes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Reportes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~\ReportesFacturacion\NoFacturable.rdlc.
        /// </summary>
        internal static string FacActividad_RptNoFacturable {
            get {
                return ResourceManager.GetString("FacActividad_RptNoFacturable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha generado la factura No {0}, el proceso fue satisfactorio.
        /// </summary>
        internal static string FacturaAlmacenada_Mensaje {
            get {
                return ResourceManager.GetString("FacturaAlmacenada_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        internal static string FacturacionAgrupada_DataSet_Detalle {
            get {
                return ResourceManager.GetString("FacturacionAgrupada_DataSet_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encabezado.
        /// </summary>
        internal static string FacturacionAgrupada_DataSet_Encabezado {
            get {
                return ResourceManager.GetString("FacturacionAgrupada_DataSet_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        internal static string FacturacionDetallada_DataSet_Detalle {
            get {
                return ResourceManager.GetString("FacturacionDetallada_DataSet_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encabezado.
        /// </summary>
        internal static string FacturacionDetallada_DataSet_Encabezado {
            get {
                return ResourceManager.GetString("FacturacionDetallada_DataSet_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NoFacturable.
        /// </summary>
        internal static string FacturacionDetallada_DataSet_NoFacturable {
            get {
                return ResourceManager.GetString("FacturacionDetallada_DataSet_NoFacturable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Cuenta.
        /// </summary>
        internal static string FacturacionEstadoCuenta {
            get {
                return ResourceManager.GetString("FacturacionEstadoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura.
        /// </summary>
        internal static string FacturacionFactura {
            get {
                return ResourceManager.GetString("FacturacionFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FacturaNoClinicaReporte.
        /// </summary>
        internal static string FacturacionNoClinica_DataSet_Reporte {
            get {
                return ResourceManager.GetString("FacturacionNoClinica_DataSet_Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen.
        /// </summary>
        internal static string FacturacionResumen {
            get {
                return ResourceManager.GetString("FacturacionResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        internal static string FacturacionResumen_DataSet_Detalle {
            get {
                return ResourceManager.GetString("FacturacionResumen_DataSet_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encabezado.
        /// </summary>
        internal static string FacturacionResumen_DataSet_Encabezado {
            get {
                return ResourceManager.GetString("FacturacionResumen_DataSet_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Cuenta.
        /// </summary>
        internal static string Facturacion_NumeroFactura {
            get {
                return ResourceManager.GetString("Facturacion_NumeroFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PSAHI.
        /// </summary>
        internal static string Facturacion_Usuario {
            get {
                return ResourceManager.GetString("Facturacion_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ReporteVenta.aspx.
        /// </summary>
        internal static string Reporte_Venta {
            get {
                return ResourceManager.GetString("Reporte_Venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        internal static string Venta_DataSet_Detalle {
            get {
                return ResourceManager.GetString("Venta_DataSet_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encabezado.
        /// </summary>
        internal static string Venta_DataSet_Encabezado {
            get {
                return ResourceManager.GetString("Venta_DataSet_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~\ReportesFacturacion\Ventas.rdlc.
        /// </summary>
        internal static string Venta_Reporte {
            get {
                return ResourceManager.GetString("Venta_Reporte", resourceCulture);
            }
        }
    }
}
